### PR TITLE
Map interface on GenericMeasurement

### PR DESCRIPTION
**Pull request by notthetup**
Adding a Map interface on GenericMeasurement Class

### CODE REVIEW

**Comment by mchitre** [comment]
Gradle changes seem to be breaking CI.

For the `Map`, all good. Just a minor feedback (no changes needed) that there's probably a simpler way to do this by simply declaring the `values` as a `@Delegate`, and not manually delegating all the methods.

**Comment by notthetup** [comment]
Oo.. I want to try to make it work with `@Delegate`. 

No idea why Gradle breaks. Maybe something to do with the `gradlew` file that Gradle added automatically?

```
0.06s$ ./gradlew check
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
```

**Comment by mchitre** [comment]
The `gradlew` thing is to automatically install gradle is not already present. Why did you need to add it? Wasn't the original gradle setup working for you, since that seemed to be working fine with CI?

**Comment by notthetup** [comment]
Right. I'll remove it. No idea why it added those files in the repo when I ran `gradle`.

**Pull request merged**
